### ISSUE TITLE
HTML picker overlay

### ISSUE THREAD

**Issue by maytis** [nolimits4web/Framework7#1323]
![screen shot 2017-01-27 at 9 40 34 pm](https://cloud.githubusercontent.com/assets/5130490/22377882/84fe8168-e4d9-11e6-8a3a-cdc7bb8318de.png)

How can I add overlay to custom html picker and close the picker when clicked anywhere on the overlay.

**Comment by ZanderBrown** [comment]
Try

```html
<div class="my-div-wrap">
    <div class="my-div">
        <!-- Content -->
    </div>
</div>
```

```css
.my-div-wrap {
    position: fixed;
    top: 0px;
    left: 0px;
    right: 0px;
    bottom: 0px;
    background: rgba(0, 0, 0, 0.6);
    z-index: 9999;
    display: none;
}

.my-div {
    position: fixed;
    bottom: 0px;
    left: 0px;
    right: 0px;
    background: rgba(255,255,255,0.9);
}
```

```javascript
function openMyDiv () {
    $('.my-div').show();
    $('.my-div-wrap').on('click', function () {
        $('.my-div').hide();
    });
}
```
