### ISSUE TITLE
Invalid CSS in kitchen sink files (?)

### ISSUE THREAD

**Issue by scriptPilot** [nolimits4web/Framework7#1565]
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
Piped kitchen sink CSS to [purify](https://github.com/purifycss/purifycss)

### Expected Behavior
CSS accepted by purify

### Actual Behavior
CSS not accepted by purify

See: https://github.com/webpack-contrib/purifycss-webpack/issues/107

**Comment by nolimits4web** [comment]
Didn't get, what exactly is incorrect there?

**Comment by valnub** [comment]
From what I understand is that he wants to remove unnecessary code from the F7 css using purifyer.

Purifyer complains though that somewhere in the css there is an syntax error or similar and thus cannot process the css.

**Comment by valnub** [comment]
Yes, I think there is indeed a syntax error:

```css
.kitchen-sink-material @media (max-width: 767px) {
  .kitchen-sink-material #ks-picker-date-container .picker-items {
    font-size: 21px;
  }
  .kitchen-sink-material #ks-picker-date-container .picker-item {
    height: 36px;
    line-height: 36px;
  }
  .kitchen-sink-material #ks-picker-date-container .picker-item span {
    padding: 0 6px;
  }
}
```

I don't think the `@media` belongs there, right? Should probably rather be:

```css
@media (max-width: 767px) {
  .kitchen-sink-material {
    .kitchen-sink-material #ks-picker-date-container .picker-items {
      font-size: 21px;
    }
    .kitchen-sink-material #ks-picker-date-container .picker-item {
      height: 36px;
      line-height: 36px;
    }
    .kitchen-sink-material #ks-picker-date-container .picker-item span {
      padding: 0 6px;
    }
  }
}
```

@scriptPilot Where did you get the code from, @scriptPilot ? Remember that the original code from F7 is LESS code, not plain css.
