### ISSUE TITLE
@media (min-width: 768px) .tabbar .toolbar-inner tabs wrong display

### ISSUE THREAD

**Issue by bigforcegun** [nolimits4web/Framework7#432]
```css

@media (min-width: 768px)
.tabbar .toolbar-inner {
  -webkit-box-pack: center;
  -ms-flex-pack: center;
  -webkit-justify-content: center;
  justify-content: center;
}

```
with justify-content tabs in toolbar displays wrong

Browser Chrome 41

example GIF
![framework7-tabbar-issue](https://cloud.githubusercontent.com/assets/264697/6627562/fe9e64c6-c90f-11e4-9b78-83b53d101895.gif)
