### ISSUE TITLE
[Material] Tabs-bar overlapping tabs-content

### ISSUE THREAD

**Issue by KLVN** [nolimits4web/Framework7#551]
If we have a Navbar and `.toolbar .tabbar` underneath it the content of `.tab` is overlapped by the navbar. Here's a fix:
```css
.page-content.tab {
  padding-top: 104px;
}
```
104px = 56px (Navbar) + 48px (Tabbar)
