### ISSUE TITLE
List items are not aligned in Firefox

### ISSUE THREAD

**Issue by Phyks** [nolimits4web/Framework7#633]
Hi,

Due to [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1208187) in Firefox, list items are not aligned.
![2015-09-25-202949](https://cloud.githubusercontent.com/assets/3856586/10108944/2ec8b22e-63c4-11e5-9717-fc2bd70a7c88.png)

Not sure how much this can be fixed in the framework side, but Firefox may not be the only browser affected by this bug.

**Comment by nolimits4web** [comment]
Yes, it is a known FF issue. I don't see/know your HTML, but basically, for usual List View, this helps:
```css
.item-title {
  width: 100%;
}

/* or */
.item-after {
  margin-left: auto;
}
```
