### ISSUE TITLE
Hairlines in LG G3

### ISSUE THREAD

**Issue by Papipo** [nolimits4web/Framework7#635]
Hi,

Hairlines like the top "border" of a card-footer aren't displayed on my device. It's a LG G3 with android 5.1.

The body classes are ```pixel-ratio-3 retina android android-5 android-5-1-1```.
I fixed the issue by adding this:

```less
html {
  &.android, &.pixel-ratio-3 {
    .card-footer:before {
      transform: scaleY(0.5);
    }
  }
}
```

I could have also applied a height: 2px; to .card-footer itself instead.

Of course I don't know what I am doing and this might break something else.
