### ISSUE TITLE
Grid Layout should support more column widths

### ISSUE THREAD

**Issue by tbcrowe** [nolimits4web/Framework7#801]
The Grid Layout system should support more columns widths, i.e. every 5%.  In particular, I think it should support col-35/tablet-35 and col-65/tablet-65 so that content blocks can be laid out to match the common 35%/65% layout of list blocks in the iOS theme.

This is the styling I came up with for 35%/65%:

```css
.row .col-35 {
  width: 35%;
  width: -webkit-calc((100% - 15px*13) / 20);
  width: calc((100% - 15px*13) / 20);
}
.row.no-gutter .col-35 {
  width: 35%;
}
.row .col-65 {
  width: 65%;
  width: -webkit-calc((100% - 15px*0.53846153846154) / 1.53846153846154);
  width: calc((100% - 15px*0.53846153846154) / 1.53846153846154);
}
.row.no-gutter .col-65 {
  width: 65%;
}
```
