### ISSUE TITLE
no-tabbar does not work well on inline-page

### ISSUE THREAD

**Issue by Poordeveloper** [nolimits4web/Framework7#803]
http://codepen.io/Poordeveloper/pen/RrVOjq

please click on "second page", on second page, the tabbar is not really undisplayed, you can see it after scrolling down.

**Comment by nolimits4web** [comment]
Just add this to your CSS:
```css
.views {
  overflow: hidden;
}
```
